### ISSUE TITLE
Minor format string issue in editable_table.py

### ISSUE THREAD

**Issue by benfry** [miguelgrinberg/flask-gridjs#1]
Got a syntax error with `editable_table.py` on these lines:

```python
User.name.like(f'%{search}%'),
User.email.like(f'%{search}%')
```

but fixed with:

```python
User.name.like(f'%%{search}%%'),
User.email.like(f'%%{search}%%')
```

Thanks for the tutorial, always appreciate your work.

**Comment by miguelgrinberg** [comment]
Why do you need to percents? One should be sufficient, I think?

**Comment by benfry** [comment]
The version of Python I was using (3.9.13 probably?) was finicky about it and wouldn't run your `editable_table.py` code without the change. 

As I understand it, this is because the `%` symbol is a special character in string formatting, the way to escape it is to use `%%`.

**Comment by miguelgrinberg** [comment]
@benfry I'm not aware of any feature in f-strings that requires percents to be escaped. Can you provide a reference?

**Comment by benfry** [comment]
Sorry, having trouble reproducing again—now I'm wondering if it was picking up a 2.x system Python that was throwing the error. 3.8 and 3.9 don't seem to have any problem with it.
