### ISSUE TITLE
Changing background opacity

### ISSUE THREAD

**Issue by Cajunlat** [miguelgrinberg/flask-gridjs#10]
Hello @miguelgrinberg !  

Is there a way to change the table background opacity?  I've managed to change the header and the footer, but not the table itself (which is inside the gridjs-wrapper class). I can change the whole table's opacity, but it affects the data being displayed.  
I have a background image that I want to slightly show through the table.

Thanks! 
Jamie

**Comment by miguelgrinberg** [comment]
@Cajunlat I suppose it is possible, but this isn't my project, so I do not know what needs to be done. Best to ask in the project discussions.
