### ISSUE TITLE
make a row element clickable

### ISSUE THREAD

**Issue by mhanuel26** [miguelgrinberg/flask-gridjs#2]
Hi @miguelgrinberg ,

I was trying to see if a row element can become clickable using jquery while using this library.

Will appreciate your help,
Thanks

**Comment by miguelgrinberg** [comment]
This project does not use jQuery, but in any case you are free to define any event handlers that you need, including click.

**Comment by mhanuel26** [comment]
Hi @miguelgrinberg ,

Thanks for coming back,

Yes I understand I can do that but I am not sure how can I add another class and href attributes to columns in table using the gridjs library. Each element will have a different href, I can however use the content of the cell as the href. 
I can use jQuery to handle the click but how can use the gridjs to insert the href?

Is this possible or am I complicating myself too much?

Thanks again,

**Comment by miguelgrinberg** [comment]
@mhanuel26 have you looked at my solution for editing cells? That includes handlers on table cells. Not a click handler, but fairly similar. You should be able to do the same to click a cell or a row.

**Comment by mhanuel26** [comment]
Hi @miguelgrinberg ,

I think I handle to insert a class and the data-href into the cell, but for some reason the element won't become clickable. 
I noticed that apparently the document ready function executes before the table is rendered

![gridjs_1](https://user-images.githubusercontent.com/2257779/179975682-f373f24f-eed6-47b0-b7fe-a3e46e0a964a.png)

I basically add this

```
        const clickableCellAttributes = (data, row, col) => {
            if (row) {
              str = removeCharRecursive(row.cells[1].data, ':')
              return {'class':'gridjs-td clickable-row', 'data-href':str};
            }
            else {
              return {};
            }
        };
```
 and then I am trying to attach the handler to the clickable-row class like this

```
        $(document).ready(function() {

          $(".clickable-row").click(function() {

            thisdata = $(this).attr('data-href');
            console.log(thisdata);

            window.location.href = thisdata;
          });
        });
```

Any idea what might be happening here?

Thanks in advance,

**Comment by miguelgrinberg** [comment]
Yes, the problem is that you are trying to set event handlers on the table cells, which grid.js creates and destroys constantly as it creates and paginates the table. When your ready handler runs the table is probably empty, so there is nothing to attach the handler to. If you look at my solution, I'm putting the event handlers on the table element, not on its children.
