### ISSUE TITLE
How would you stripe the gridjs table and select different colors?

### ISSUE THREAD

**Issue by jwmurray** [miguelgrinberg/flask-gridjs#7]
In the first first table tutorial, the table was striped.  

I have been trying to figure out how to add the CSS to make this gridjs table striped, but I am not succeeding.  Any help would be appreciated.

thank you

**Comment by miguelgrinberg** [comment]
There are many tutorials that show how to style a table with stripes. First result Google gives me is https://www.geeksforgeeks.org/how-to-create-a-zebra-striped-table-with-css/.

You may not need this, but the grid.js documentation shows how to provide styles directly as options to the grid.js constructor: https://gridjs.io/docs/examples/css-style

**Comment by jwmurray** [comment]
Finally figured it out.  The problem is that gridjs does not allow "tr:nth-child(even)" to pass through it's "style" section.  I don't think "tr" is passed through at all.

The solution is to select the even rows in the page header, and then to modify the `td` fields in those rows:

This SO question solves the problem: https://stackoverflow.com/questions/75501116/how-to-create-different-background-for-my-table-row-nth-child

While you cannot affect the background of TR directly, you can select the TD's of the Even TR's and then apply the color to those TD's as shown in this SO question.  Change the CSS in the page header:

`<html>
    <head>
        <title>Rule Table</title>
        <link href="https://unpkg.com/gridjs/dist/theme/mermaid.min.css" rel="stylesheet" />
        <style>
...
            
            .gridjs-tr:nth-child(even) td {
                background: #dfdfdf;
            }
...

        </style>
    </head>`
