### ISSUE TITLE
Slow on Editable table

### ISSUE THREAD

**Issue by jwmurray** [miguelgrinberg/flask-gridjs#8]
I find that with 1000 users in the editable table, it has good response times.

However, when I add my own data, the response after each key stroke takes about 1 second, often missing keys.

I have tried reducing the number of members of the User model, but still get slow responses.  I am sure it is something with my code, but the I am not seeing it.  What have you seen that kills response times on the editable table?

thank you.

**Comment by miguelgrinberg** [comment]
I honestly don't know. I don't think there is any relationship between the editable feature and how many items there are in the database. I have a database with 10,000 users and I can edit any of them without any noticeable delay. Besides, no requests are sent to the server while editing a field, so the size of the database doesn't really matter at all.

**Comment by jwmurray** [comment]
Thank you.
