### ISSUE TITLE
Bug: 'start' value (sometimes) broken in pagination

### ISSUE THREAD

**Issue by CodeFinder2** [miguelgrinberg/flask-gridjs#9]
First off, thanks for the this cool demo/example! :-)

I came across the following bug (steps to reproduce):
- Create user: `python create_fake_users.py 10000`. (Better: use [attached database file](https://github.com/miguelgrinberg/flask-gridjs/files/12411036/db.zip). ;-) GitHub does not support uploading sqlite files, that's why its zipped.)
- Search for "David" and directly go to the last page (press the "32" button in the lower right).
- Quickly search for "Anna" now. Seems like doing this "quickly" isn't even really necessary.
- The result page will **contain no results** (empty table) although there are results and Gridjs confirms this by summarizing "Showing 1 to 10 of 157 results". See the following screenshot.
<img src="https://github.com/miguelgrinberg/flask-gridjs/assets/20599588/1c288b45-865e-467c-a445-d9f33f0f94e3" width="500">

Adding the debug code (to the `data()` function):
```python
    if start != -1 and length != -1:
        print(f"Offsetting: {start}, {length}")
        query = query.offset(start).limit(length)
```
reveals that the `start` value is still containing the previous start value (`Offsetting: 310, 10`) of the last page when showing previous search results (for "David", in this case). To easier reproduce it, I've attached by generated SQLite database file.

Can you fix this or explain how it can be fixed?

Thank you so much!

**Comment by miguelgrinberg** [comment]
I honestly do not think this is a bug, but this is a behavior of grid.js, so if this is a bug, it is not a bug in this project, which just demonstrates how to integrate grid.js with Flask.

In any case, you are on page 32, and you change the search parameters such that the new search results have less than 32 pages. The table is empty because you are still on page 32, which is past the end of the new result set. If you click on any of the pages shown in the bottom right you will go to the correct page for the new search.

**Comment by CodeFinder2** [comment]
Thanks for you quick response.

I agree with your explanation of why the table is (considered) empty. 

But how can this be "the behavior of grid.js" if you provide wrong parameters in the python code to the pagination?

Anyway, do think this is fixable from Python? Testing whether the start is "out-of-scope" seems like a bad idea. I would say, the current page needs to be reset when a new search term is entered. What do your think?

**Comment by CodeFinder2** [comment]
Alight, guess I fixed it that way (testing whether the search string has changed). Thanks anyay!

**Comment by miguelgrinberg** [comment]
> But how can this be "the behavior of grid.js" if you provide wrong parameters in the python code to the pagination?

Simple. Try the `basic_table.py` example, which downloads the entire list of people to the client and then does the pagination entirely there.

You may be able to detect this in the server as you indicated, but I believe that will produce a state difference between the server (which is now maybe on page 1) and the client (which still thinks it's on page 32).
